# Generated by Django 4.1.5 on 2023-01-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event", name="description", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.CharField(
                default="/static/img/default_event.png", max_length=1000
            ),
        ),
    ]
