# Generated by Django 4.1.5 on 2023-01-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_event_full_description_event_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="eventtag", name="event",),
    ]
