# Generated by Django 4.1.5 on 2023-01-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_eventtag_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(blank=True, to="app.eventtag"),
        ),
    ]
