# Generated by Django 4.1.5 on 2023-01-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_event_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequiredSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="required_skills",
            field=models.ManyToManyField(blank=True, to="app.requiredskill"),
        ),
    ]
