# Generated by Django 4.1.5 on 2023-01-31 16:34

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_requiredskill_team_required_skills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team", old_name="users", new_name="members",
        ),
        migrations.AddField(
            model_name="team",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.upload_to
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="leader",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
