# Generated by Django 4.1.5 on 2023-02-04 16:46

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_rename_users_team_members_team_image_team_leader"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=app.models.upload_to
                    ),
                ),
                ("url", models.URLField(blank=True, default="")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.team"
                    ),
                ),
            ],
        ),
    ]
