# Generated by Django 4.1.5 on 2023-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_actionnotification_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="actionnotification", name="type",),
        migrations.AddField(
            model_name="actionnotification",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("join_request", "join_request"),
                    ("invite_request", "invite_request"),
                    ("kick", "kick"),
                ],
                default="join",
                max_length=20,
            ),
        ),
    ]
