# Generated by Django 4.1.5 on 2023-02-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_actionnotification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionnotification",
            name="is_accepted",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
