# Generated by Django 4.1.5 on 2023-02-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_actionnotification_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionnotification',
            name='action_type',
            field=models.CharField(choices=[('join_request', 'join_request'), ('invite_request', 'invite_request'), ('kick', 'kick'), ('member_left', 'member_left')], default='join', max_length=20),
        ),
    ]
